### ISSUE TITLE
Compilation Error on version 0.7.0

### ISSUE THREAD

**Issue by rjgroller** [philosodad/morphix#23]
Hello, 

I'm receiving the following error when trying to compile my app with version 0.7.0:

```elixir
== Compilation error in file lib/morphix.ex ==
** (CompileError) lib/morphix.ex:862: imported Kernel.is_struct/1 conflicts with local function
    (elixir 1.10.3) src/elixir_locals.erl:94: :elixir_locals."-ensure_no_import_conflict/3-lc$^0/1-0-"/2
    (elixir 1.10.3) src/elixir_locals.erl:95: anonymous fn/3 in :elixir_locals.ensure_no_import_conflict/3
    (stdlib 3.9.2) erl_eval.erl:680: :erl_eval.do_apply/6
```

**Comment by philosodad** [comment]
That issue is solved in version 0.8.0, it's an incompatibility with elixir 1.10.

**Comment by rjgroller** [comment]
Thanks for the quick response! So I don't see a tagged v0.8.0 in the repo and hex did seem to be pulling down an incorrect version of morphix as well.

**Comment by philosodad** [comment]
There isn't a tag... I must have missed that, although I think there is a hex package that should fix this. I've added you as a collaborator if you're in a hurry to fix this, otherwise it might be a few hours before I get to it.

**Comment by rjgroller** [comment]
I'm not sure what hex package you are talking about, so I can wait for you to look at it unless you can provide a little direction on that.

**Comment by philosodad** [comment]
https://hex.pm/packages/morphix/0.8.0 should solve this issue.
There is a tag for v0.8.0.
I tested this morning using elixir 1.6.1/erlang 20 and 1.10.3/erlang 22
If you're still experiencing this problem let me know more about your configuration.

**Comment by rjgroller** [comment]
I think you can close this - the hex tag for 0.8.0 does seem to work. I think all that might be needed is to git tag v0.8.0
